# Generated by Django 5.0.2 on 2025-04-20 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daymenu',
            name='sides',
            field=models.ManyToManyField(related_name='side_dish_days', to='calendar_app.meal'),
        ),
        migrations.AddField(
            model_name='userselection',
            name='selected_side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_sides', to='calendar_app.meal'),
        ),
    ]
