# Generated by Django 5.0.2 on 2025-04-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_auto_20250420_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='is_complete_dish',
            field=models.BooleanField(default=False, verbose_name='Полноценное блюдо'),
        ),
        migrations.AlterField(
            model_name='daymenu',
            name='day',
            field=models.CharField(choices=[('MON', 'Понедельник'), ('TUE', 'Вторник'), ('WED', 'Среда'), ('THU', 'Четверг'), ('FRI', 'Пятница')], max_length=3),
        ),
    ]
