# Generated by Django 5.0.2 on 2025-04-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_meal_is_complete_dish_alter_daymenu_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselection',
            name='not_eating',
            field=models.BooleanField(default=False, verbose_name='Не ем'),
        ),
    ]
