# Generated by Django 5.0.2 on 2025-04-22 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_userselection_not_eating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daymenu',
            options={'ordering': ['date'], 'verbose_name': 'Меню на день', 'verbose_name_plural': 'Меню по дням'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Категория блюд', 'verbose_name_plural': 'Категории блюд'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['category', 'excel_row', 'name'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='userselection',
            options={'ordering': ['day_menu', 'user'], 'verbose_name': 'Выбор пользователя', 'verbose_name_plural': 'Выборы пользователей'},
        ),
        migrations.RemoveField(
            model_name='daymenu',
            name='day',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='selection_date',
        ),
        migrations.AddField(
            model_name='meal',
            name='excel_row',
            field=models.IntegerField(blank=True, help_text='Строка в Excel для этого блюда', null=True),
        ),
        migrations.AlterField(
            model_name='daymenu',
            name='bakery',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name': 'Выпечка'}, related_name='day_menus_as_bakery', to='calendar_app.meal'),
        ),
        migrations.AlterField(
            model_name='daymenu',
            name='main_courses',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name': 'Горячие блюда'}, related_name='day_menus_as_main', to='calendar_app.meal'),
        ),
        migrations.AlterField(
            model_name='daymenu',
            name='salads',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name': 'Салаты'}, related_name='day_menus_as_salad', to='calendar_app.meal'),
        ),
        migrations.AlterField(
            model_name='daymenu',
            name='sides',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name': 'Гарниры'}, related_name='day_menus_as_side', to='calendar_app.meal'),
        ),
        migrations.AlterField(
            model_name='daymenu',
            name='soups',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category__name': 'Супы'}, related_name='day_menus_as_soup', to='calendar_app.meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, help_text='Полное описание блюда с ингредиентами', null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='is_complete_dish',
            field=models.BooleanField(default=False, help_text='Является ли блюдо полноценным (не требует гарнира)'),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='not_eating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='selected_bakery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_as_bakery', to='calendar_app.meal'),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='selected_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_as_main', to='calendar_app.meal'),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='selected_salad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_as_salad', to='calendar_app.meal'),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='selected_side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_as_side', to='calendar_app.meal'),
        ),
        migrations.AlterField(
            model_name='userselection',
            name='selected_soup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_as_soup', to='calendar_app.meal'),
        ),
    ]
