# Generated by Django 5.2 on 2025-04-13 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDishSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_planner.dish')),
            ],
            options={
                'verbose_name': 'Сохраненное блюдо',
                'verbose_name_plural': 'Сохраненные блюда',
            },
        ),
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название сохранения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dishes', models.ManyToManyField(through='meal_planner.SavedDishSelection', to='meal_planner.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сохраненный выбор',
                'verbose_name_plural': 'Сохраненные выборы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='saveddishselection',
            name='user_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_planner.userselection'),
        ),
        migrations.AlterUniqueTogether(
            name='saveddishselection',
            unique_together={('user_selection', 'dish')},
        ),
    ]
