# Generated by Django 5.2 on 2025-04-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0002_saveddishselection_userselection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishselection',
            options={'verbose_name': 'Выбор блюда', 'verbose_name_plural': 'Выборы блюд'},
        ),
        migrations.AddField(
            model_name='dishselection',
            name='saved',
            field=models.BooleanField(default=False, verbose_name='Сохранено'),
        ),
        migrations.AddField(
            model_name='dishselection',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата сохранения'),
        ),
    ]
