# Generated by Django 5.2 on 2025-04-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0003_alter_dishselection_options_dishselection_saved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userselection',
            name='dishes',
        ),
        migrations.RemoveField(
            model_name='userselection',
            name='user',
        ),
        migrations.DeleteModel(
            name='SavedDishSelection',
        ),
        migrations.DeleteModel(
            name='UserSelection',
        ),
    ]
