# Generated by Django 5.2 on 2025-04-13 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0004_remove_userselection_dishes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сохраненный выбор',
                'verbose_name_plural': 'Сохраненные выборы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedDishSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_planner.dish')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='meal_planner.userselection')),
            ],
            options={
                'verbose_name': 'Сохраненное блюдо',
                'verbose_name_plural': 'Сохраненные блюда',
            },
        ),
    ]
