# Generated by Django 5.2 on 2025-04-13 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0005_userselection_saveddishselection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['name'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('salad', 'Салаты'), ('soup', 'Супы'), ('main', 'Горячее'), ('side', 'Гарниры'), ('bakery', 'Выпечка'), ('fasting', 'Постная еда')], default='main', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='dish',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='dish',
            name='is_fasting',
            field=models.BooleanField(default=False, verbose_name='Постное блюдо'),
        ),
        migrations.AddField(
            model_name='dish',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название блюда'),
        ),
    ]
